envVariables:
  ServiceSettings__MessageBroker : SERVICEBUS
  ServiceSettings__KeyVaultName : microshop
  SeqSettings__Host: seq.observability
  SeqSettings__Port: 5341
  JaegerSettings__Host: jaeger-query.observability
  JaegerSettings__Port: 14317


container:
  liveness:
    path: /health/live
    initialDelaySeconds: 10
  readiness:
    path: /health/ready
    initialDelaySeconds: 10

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

service:
  type: ClusterIP
  port: 80

