apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{.Values.microserviceName}}-service"
  labels:
    appType: {{.Chart.Name}}
spec:
  selector:
    matchLabels:
      appType: {{.Chart.Name}}
  endpoints:
    - port: http
